# Numpy Assignment

### Problem 1

Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N -i -1.

In [12]:
import numpy as np

from abc import ABCMeta, abstractmethod

class AbstactBaseVanderMatrix(metaclass=ABCMeta):
    def __init__(self): pass
    @abstractmethod
    def generate_vander_matrix(self): pass
    
class VanderMatrix(AbstactBaseVanderMatrix):
    def __init__(self, p_vector):
        self._vector = p_vector
        
    def generate_vander_matrix(self):
        col = int(input("Enter number of columns you want to generate in Vandermonde matrix (3 to 5): "))
        if col<3 or col>5:
            raise ValueError("'Wrong Entry. Enter between 3 to 5.'")
        order = int(input("Enter order of matrix. (1-for Increasing or 2-for decreasing: "))
        if order !=1 and order!=2:
            raise ValueError("'Wrong Entry. Enter between 1 or 2.'")
        elif order ==1:
            vander_matrix = np.vander(self._vector,col,increasing=True)
        else:
            vander_matrix = np.vander(self._vector,col,increasing=False)
        # Now print the matrix
        print("\n",vander_matrix) 


# Create a local vector and pass it to the object.
l_vector = np.array([1,2,3,4,5])

try:
    VanderMatrixObj = VanderMatrix(l_vector)
        
except Exception as e:
    print("{0}:Exception: Object initialisation error: {1}".format(type(e),e))
else:
    print("\nObject initialised successfully...\n")
    try:
        # Generate and print Vander Matrix
        VanderMatrixObj.generate_vander_matrix()
        VanderMatrixObj.generate_vander_matrix()
        VanderMatrixObj.generate_vander_matrix()
        VanderMatrixObj.generate_vander_matrix()
                
    except Exception as e:
        print("{0}:Exception: Generating Vandermon Matrix: {1}".format(type(e),e))
finally:
    del VanderMatrixObj
    print("\nObject deleted successfully...") 


Object initialised successfully...

Enter number of columns you want to generate in Vandermonde matrix (3 to 5): 5
Enter order of matrix. (1-for Increasing or 2-for decreasing: 1

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Enter number of columns you want to generate in Vandermonde matrix (3 to 5): 5
Enter order of matrix. (1-for Increasing or 2-for decreasing: 2

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Enter number of columns you want to generate in Vandermonde matrix (3 to 5): 3
Enter order of matrix. (1-for Increasing or 2-for decreasing: 1

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
Enter number of columns you want to generate in Vandermonde matrix (3 to 5): 3
Enter order of matrix. (1-for Increasing or 2-for decreasing: 2

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]

Object deleted successfully.

# Problem 2

Question:Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3


In [15]:
import numpy as np

from abc import ABCMeta, abstractmethod

class AbstactBaseMovingAverage(metaclass=ABCMeta):
    def __init__(self): pass
    @abstractmethod
    def moving_average(self): pass
    
class MovingAverage(AbstactBaseMovingAverage):
    def __init__(self, p_list, p_window):
        self._list = p_list
        self._window = p_window
        
    def moving_average(self):
        self._mov_avg = np.cumsum(self._list, dtype=float)
        self._mov_avg[self._window:] = self._mov_avg[self._window:] - self._mov_avg[:-self._window]
        return self._mov_avg[self._window - 1:] / self._window

# Create a local list and pass it to the object.
l_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
l_window = 3
    
try:
    MovingAvgObj = MovingAverage(l_list, l_window)
        
except Exception as e:
    print("{0}:Exception: Object initialisation error: {1}".format(type(e),e))
else:
    print("\nObject initialised successfully...\n")
    try:
        # Calculate Moving Average
        mov_avg = MovingAvgObj.moving_average()
        print("Moving average list with {} elements :\n\n{}".format(len(mov_avg),mov_avg))
                
    except Exception as e:
        print("{0}:Exception: Calculating moving average: {1}".format(type(e),e))
finally:
    del MovingAvgObj
    print("\nObject deleted successfully...") 


Object initialised successfully...

Moving average list with 11 elements :

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]

Object deleted successfully...
